name: Release

on:
  push:
#  workflow_dispatch:
#    inputs:
#      pre-release:
#        required: false
#        type: boolean
#        default: false
#        description: "This release will be labeled as non-production ready"
#      github-release:
#        required: false
#        type: boolean
#        default: false
#        description: "Publish Github release for the current version"
#  # Monitor pull request events
#  pull_request:
#    types:
#      - closed
#    branches:
#      - main

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare the next main release
        uses: Adyen/release-automation-action@v1.3.1
        with:
          token: ${{ secrets.ADYEN_AUTOMATION_BOT_ACCESS_TOKEN }}
          develop-branch: main
          version-files: package.json
          release-title: Adyen Magento-2 Plugin
          pre-release: ${{ inputs.pre-release || false }}
          github-release: ${{ inputs.github-release || false }}
          separator: .pre.beta
